spring:
  application:
    name: EC04EGOAVIL
    
########## H2SQL #################
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:ec04egoavil;DB_CLOSE_ON_EXIT=FALSE
#    username: root
#   password: rodrihawk#123
#    driver-class-name: org.h2.Driver
    
########## MYSQL #################
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/ec04egoavil
    username: root
    password: rodrihawk#123
    driver-class-name: com.mysql.jdbc.Driver
